version: 2

sources:
  - name: dbt_nyc_motor_crash
    schema: nyc_motor_vehicle_collision_dataset
    tables:
      - name: nyc_motor_crashes


models:
  - name: stg_2025_nyc_crashes
    description: 
      The Motor Vehicle Collisions crash table contains details on the crash event. Each row represents a crash event. 
      The Motor Vehicle Collisions data tables contain information from all police reported motor vehicle collisions 
      in NYC. The police report (MV104-AN) is required to be filled out for collisions where someone is injured or killed, 
      or where there is at least $1000 worth of damage 
      (https://www.nhtsa.gov/sites/nhtsa.dot.gov/files/documents/ny_overlay_mv-104an_rev05_2004.pdf). 
      It should be noted that the data is preliminary and subject to change when the MV-104AN forms are amended 
      based on revised crash details. For the most accurate, up to date statistics on traffic fatalities, 
      please refer to the NYPD Motor Vehicle Collisions page (updated weekly) or Vision Zero View (updated monthly).

    columns:
      - name: crash_date
        description: Occurence date of collision.
      - name: crash_time
        description: Occurence time of collision.
      - name: on_street_name
        description: Street on which the collision occurred.
      - name: off_street_name
        description: Nearest cross street to the collision.
      - name: number_of_persons_injured
        description: Number of persons injured.
      - name: number_of_persons_killed
        description: Number of persons killed.     
      - name: number_of_pedestrians_injured
        description: Number of pedestrians injured.
      - name: number_of_pedestrians_killed
        description: Number of pedestrians killed.
      - name: number_of_cyclist_injured
        description: Number of cyclists injured.
      - name: number_of_cyclist_killed
        description: Number of cyclists killed.
      - name: number_of_motorist_injured
        description: Number of motorists injured.
      - name: number_of_motorist_killed
        description: Number of motorists killed.
      - name: contributing_factor_vehicle_1
        description: Factors contributing to the collision for designated vehicle.
      - name: contributing_factor_vehicle_2
        description: Factors contributing to the collision for designated vehicle.
      - name: collision_id
        description: Unique record code generated by system. Primary key for Crash table
        tests:
          - unique
          - not_null
      - name: vehicle_type_code_1
        description: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)
      - name: vehicle_type_code_2
        description: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other)
      - name: borough
        description: Borough where collision occurred.
      - name: zip_code
        description: Postal code of incident occurrence.
      - name: latitude
        description: Latitude coordinate for Global Coordinate System, WGS 1984 decminal degress(EPSG 4326).
      - name: longitude
        description: Longitude coordinate for Global Cordinate System, 4gs 1984, deicmal degrees (EPSG 4326).
      - name: location
        description: Latitude, Longitude pair.
      - name: contributing_factor_vehicle_3
        description: Factors contributing to the collision for designated vehicle.
      - name: vehicle_type_code_3
        description: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other).
      - name: cross_street_name
        description: Street address if known.
      - name: contributing_factor_vehicle_4
        description: Factors contributing to the collision for designated vehicle.
      - name: vehicle_type_code_4
        description: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other).
      - name: contributing_factor_vehicle_5
        description: Factors contributing to the collision for designated vehicle.
      - name: vehicle_type_code_5
        description: Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other).

